### ISSUE TITLE
Remove nodejs v16 support

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-js#195]
Nodejs v16 is EOL on September 11th https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by slvrtrn** [comment]
@davojan @mlent, I see you reacted with a thumbs down on this issue, so let me explain it a bit.

The removal of Node.js 16.x "support" in our case means only that we will remove it from the CI runs, so the test matrix will be `[18.x, 20.x, 21.x]` instead of `[16.x, 18.x., 20.x]`. There is a very high chance that, for the time being, the library will still be compatible with the outdated versions, as it is not like we are building separate packages for each node version.
