### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by ReginYuan** [ClickHouse/clickhouse-js#219]
@clickhouse\client-common\dist\client.js:137:19)  我在做删除指定删除数据库中的表的字段时报错：TypeError: Cannot read properties of undefined (reading 'trim')

> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
<img width="845" alt="微信图片_20231228172643" src="https://github.com/ClickHouse/ClickHouse/assets/49477488/a7c6fd43-cabc-4c9c-8d8c-329e1a7c8801">
<img width="857" alt="微信图片_20231228172651" src="https://github.com/ClickHouse/ClickHouse/assets/49477488/ef6bb0a1-d9bc-457b-af79-0e52c5e20828">

**Comment by slvrtrn** [comment]
@ReginYuan, do you use the `query` method like it's shown in this example: https://github.com/ClickHouse/clickhouse-js/blob/main/examples/select_json_each_row.ts#L7-L10? (see the params passed as an object with `query` property)

**Comment by mshustov** [comment]
@slvrtrn maybe we should add a simple runtime validation for required fields? Not everyone uses typescript.

**Comment by slvrtrn** [comment]
@mshustov, I'd argue that 
1) even in vanilla JS, code editors such as VS Code give type hints since those are embedded in the package:

<img width="948" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/3175289/b4dc10b4-2256-4a43-88c0-fbb7c1cfdb9e">

2) if you click on the `query` method and then to `QueryParams`, all the types are still there to explore

<img width="636" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/3175289/0ace545a-e5d1-4424-972c-33d3e14d2b0c">

3) API is thoroughly covered in [the docs](https://clickhouse.com/docs/en/integrations/language-clients/javascript#query-method)

4) Finally, TS should be considered; it's 2024 already.
