### ISSUE TITLE
10s delay when sending concurrent queries with `max_open_connections=1`

### ISSUE THREAD

**Issue by nikhilro** [ClickHouse/clickhouse-js#348]
### Describe the bug
There is an unexpected 10s delay when sending concurrent queries with `max_open_connections=1`

### Steps to reproduce
```
import { createClient } from '@clickhouse/client';

async function queryRun(client: any, index: number) {
  const query = `SELECT 1`;

  const start = Date.now();
  const [result1, result2] = await Promise.all([
    client.query({ query }),
    client.query({ query }),
  ]);

  const [json1, json2] = await Promise.all([result1.json(), result2.json()]);

  const elapsed = Date.now() - start;
  console.log(
    `Run ${index + 1} took: ${elapsed}ms (${json1.rows},${json2.rows})s`,
  );
}

async function main() {
  const client = createClient({
    host: process.env.CLICKHOUSE_HOST,
    password: process.env.CLICKHOUSE_PASSWORD,
    max_open_connections: 1,
  });

  for (let i = 0; i < 10; i++) {
    await queryRun(client, i);
  }
}

main().catch(console.error);
```

Result:
```
Run 1 took: 10280ms (1,1)
Run 2 took: 10147ms (1,1)
Run 3 took: 10204ms (1,1)
Run 4 took: 10149ms (1,1)
Run 5 took: 10152ms (1,1)
Run 6 took: 10148ms (1,1)
Run 7 took: 10143ms (1,1)
Run 8 took: 10139ms (1,1)
Run 9 took: 10134ms (1,1)
Run 10 took: 10202ms (1,1)
```

### Expected behaviour
Changing above to 
```
  const [result1, result2] = await Promise.all([
    client.query({ query }),
    Promise.resolve({ json: () => ({ data: [], rows: 1 }) }),
  ]);
```

Result:
```
Run 1 took: 198ms (1,1)
Run 2 took: 36ms (1,1)
Run 3 took: 38ms (1,1)
Run 4 took: 37ms (1,1)
Run 5 took: 36ms (1,1)
Run 6 took: 36ms (1,1)
Run 7 took: 35ms (1,1)
Run 8 took: 35ms (1,1)
Run 9 took: 39ms (1,1)
Run 10 took: 36ms (1,1)
```

#### Environment
* Client version: 1.6.0
* Language version: Node
* OS: MacOS

#### ClickHouse server
* ClickHouse Server version: 24.8.1.10338
* ClickHouse Server non-default settings, if any: NA
* `CREATE TABLE` statements for tables involved: NA
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary: NA

**Comment by slvrtrn** [comment]
Currently, it looks like this depends on the 

```
<clickhouse>
 <keep_alive_timeout>N</keep_alive_timeout>
</clickhouse>
```

setting from config.xml.

Setting it as 2 makes it 
```
Run 1 took: 2016ms (1,1)s
Run 2 took: 2006ms (1,1)s
Run 3 took: 2006ms (1,1)s
Run 4 took: 2007ms (1,1)s
Run 5 took: 2007ms (1,1)s
Run 6 took: 2006ms (1,1)s
Run 7 took: 2006ms (1,1)s
Run 8 took: 2006ms (1,1)s
Run 9 took: 2007ms (1,1)s
Run 10 took: 2006ms (1,1)s
```

I will investigate what holds the connection back in this case cause I'd expect that the other query should be executed ASAP when the first one from the "batch" is finished.

**Comment by slvrtrn** [comment]
The problematic part in your code is this:

```ts
  const [result1, result2] = await Promise.all([
    client.query({ query }),
    client.query({ query }),
  ]);

  const [json1, json2] = await Promise.all([result1.json(), result2.json()]);
```

What happens: having only one connection available, with this

```ts
  const [result1, result2] = await Promise.all([
    client.query({ query }),
    client.query({ query }),
  ]);
```

Without consuming the result set immediately, the first query will hold the socket until it is closed by ClickHouse, which is regulated by that keep_alive_timeout server setting; only then will the second query be executed after the first one timed out, as a new socket becomes available in the internal connection pool. 

As the query is only `SELECT 1`, the entire data is sent immediately with the response, so it doesn't fail explicitly.

The correct approach is to run query + process the result set as soon as it is available, for example:

```ts
async function queryRun(client: NodeClickHouseClient, query: string) {
  const resultSet = await client.query({ query })
  return resultSet.json() // <- fetch the data immediately!
}

async function batchRun(client: NodeClickHouseClient, index: number) {
  const _query = `SELECT 1`

  const start = Date.now()
  const [json1, json2] = await Promise.all([
    queryRun(client, _query),
    queryRun(client, _query),
  ])

  const elapsed = Date.now() - start
  console.log(
    `Run ${index + 1} took: ${elapsed}ms (${json1.rows},${json2.rows})s`,
  )
}

async function main() {
  const client = createClient({
    max_open_connections: 1,
  })

  for (let i = 0; i < 10; i++) {
    await batchRun(client, i)
  }
}
```

In this case, everything works as expected:

```
Run 1 took: 12ms (1,1)s // <- this is a tad bit slower as it isn't KeepAlive yet
Run 2 took: 3ms (1,1)s
Run 3 took: 3ms (1,1)s
Run 4 took: 3ms (1,1)s
Run 5 took: 3ms (1,1)s
Run 6 took: 3ms (1,1)s
Run 7 took: 3ms (1,1)s
Run 8 took: 3ms (1,1)s
Run 9 took: 2ms (1,1)s
Run 10 took: 2ms (1,1)s
```

Side note: in your example, the main does not fail only because the query is `SELECT 1`, which yields the entire response data immediately; replacing the query with something like `SELECT * FROM system.numbers LIMIT 1000`, especially with a reduced `request_timeout` setting will illustrate that the socket just times out

```
  Message:
    Error: aborted
  Stack:
    error properties: Object({ code: 'ECONNRESET' })
        at connResetException (node:internal/errors:787:14)
        at Socket.socketCloseListener (node:_http_client:455:19)
        at Socket.emit (node:events:526:35)
        at Socket.emit (node:domain:488:12)
        at TCP.<anonymous> (node:net:337:12)
```

Regarding ResultSet consumption on the application side, there are a few mentions in the client docs on the website about this, see https://clickhouse.com/docs/en/integrations/javascript#query-method and https://clickhouse.com/docs/en/integrations/javascript#resultset-and-row-abstractions in particular.
