### ISSUE TITLE
Add Nested data type support

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-js#89]
See https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested

Fix the [failing test.](https://github.com/ClickHouse/clickhouse-js/blob/8a8ce2bde95ebc0b557bae1d1cba23c00b44405e/__tests__/integration/data_types.test.ts#L472-L523)

**Comment by antoniovizuete** [comment]
Hi @slvrtrn!

I'm willing to work on adding support for nested data types.

My approach would be to flatten the nested structures, such as objects. So, I would choose the `Record<K, V>` TS type to support the `**Nested**`data type, because both have the same goal, to handle structured data.

If we assume the explanation, then we face incompatibility with the `Map(K, V)` data type. According to the **[[official docs](https://clickhouse.com/docs/en/integrations/language-clients/nodejs#supported-clickhouse-data-types)](https://clickhouse.com/docs/en/integrations/language-clients/nodejs#supported-clickhouse-data-types)**, the `Map(K, V)` data type is supported by the `Record<K, V>` TS type.

This means that I won’t be able to differentiate between `Map` and `Nested` when attempting to flatten them.

In my opinion, the `Map(K, V)` data type should be supported by the `Map<K, V>` TS type. There are a couple of advantages to supporting it as a TS Map:

- It would create semantic coherence between the Clickhouse data type and the TS type.
- The TS Map API is better suited for handling data map structures than the TS Record type.

What do you think about supporting Clickhouse Map with TS Map?

Many thanks
