### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-js#96]
Likely only for security updates.

**Comment by ultram4rine** [comment]
According to the [doc](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories), dependabot only for security updates can be configured in repository settings. But it should be already enabled since this repo is public:
> For public repositories, the button is disabled if the feature is always enabled.

Another more explicit option is to add `.github/dependabot.yml` with `open-pull-requests-limit` setting set to 0.
